name: PHP Setup
on:
  workflow_call:
    inputs:
      php-version:
        required: false
        type: string
        default: '8.2'
jobs:
  setup-php:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup PHP
        uses: ./.github/actions/setup-php
        with:
          coverage: none
